#!/bin/bash
export PYTHONPATH=`pwd`
python framework/webserver/webServer.py &
python framework/components/control.py  &
python interfaces/wsInterface.py &
python applications/snakeApp/snakeApp.py &
python applications/clockApp/clockApp.py &
python applications/colourTestApp/colourTestApp.py &
python displays/ledDisplayStart.py &
