#!/bin/bash
PYTHONPATH=`pwd`
export PYTHONPATH
python framework/webserver/webServer.py &
python framework/components/control.py config.json &
python interfaces/wsInterface.py &
python applications/snakeApp/snakeApp.py &
python applications/clockApp/clockApp.py &
python applications/colourTestApp/colourTestApp.py &
displays/ledDisplay &
