document.write("   <div class=\"navmenu navmenu-default navmenu-fixed-left offcanvas\">");
document.write("      <a class=\"navmenu-brand\" href=\"#\">WordClock</a>");
document.write("      <ul class=\"nav navmenu-nav\">");
document.write("        <li id=\"nav-status\"><a href=\"/index.html\"><b>Status</b></a></li>");
document.write("      </ul>");
document.write("      <ul class=\"nav navmenu-nav\">");
document.write("        <li id=\"nav-clock\"><a href=\"/applications/clockApp/\">Clock</a></li>");
document.write("        <li id=\"nav-color\"><a href=\"/applications/colourTestApp/\">ColourTest</a></li>");
document.write("      </ul>");
document.write("      <ul class=\"nav navmenu-nav\">");
document.write("        <li id=\"nav-settings\"><a href=\"/globalSettings/\"><b>Global Settings</b></a></li>");
document.write("      </ul>");
document.write("    </div>");
document.write("");
document.write("    <div class=\"navbar navbar-default navbar-fixed-top\">");
document.write("      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"offcanvas\" data-target=\".navmenu\" data-canvas=\"body\">");
document.write("        <span class=\"icon-bar\"></span>");
document.write("        <span class=\"icon-bar\"></span>");
document.write("        <span class=\"icon-bar\"></span>");
document.write("      </button>");
document.write("    </div>");
